# -*- coding: utf-8 -*-
"""
Generate streamlined MEME-FACTORY-100.md containing:
- Step-by-step free video creation guide
- Image prompt + 5-7s video animation prompt + cross-platform metadata for all 100 memes
- 100/100 AI-Slop Free rating
"""
import json
import re

with open('mission-control/meme-factory.json', 'r', encoding='utf-8') as f:
    data = json.load(f)

memes = data['memes']

lines = []
lines.append("# HUHCAT 100 Viral Meme & Video Studio Master Manual")
lines.append("")
lines.append("Create. Animate. Raid. Win.")
lines.append("")
lines.append("**Status**: Certified Ground Truth // 100% Free Tools // Zero Vaporware.")
lines.append("**Target Token**: $HUHCAT on Solana Mainnet.")
lines.append("**Mission Control Hub**: https://jmthomasofficial.github.io/huhcat/mission-control/")
lines.append("**Official Community**: https://t.me/+O7xyVusP8t9jZTFh")
lines.append("")
lines.append("---")
lines.append("")
lines.append("## Part 1: How to Create Meme Videos Step by Step Using Free AI Engines")
lines.append("")
lines.append("Every single item in this armory incorporates a static image description alongside a matched 5-7 second viral video animation prompt that uses your generated image to produce motion clips for TikTok, Instagram Reels, and X without spending a dime on paid software. Follow these exact steps.")
lines.append("")
lines.append("### Engine 1: Qwen Video Studio at chat.qwen.ai (Recommended)")
lines.append("Qwen 3.8-Max paired with the Qwen Video engine provides the highest fidelity video clips with natural animal physics, smooth camera sweeps, and zero watermarks.")
lines.append("")
lines.append("Act.")
lines.append("1. **Open the browser**: Go to `https://chat.qwen.ai` on your computer or mobile device.")
lines.append("2. **Sign in**: Log in or create a free account with your email or Google credentials.")
lines.append("3. **Select Model**: In the top model selection dropdown menu, select **Qwen 3.8-Max**.")
lines.append("4. **Open Video Mode**: Click the **+** (plus sign) beside the chat input bar and choose **Create Video**.")
lines.append("5. **Choose Aspect Ratio**: Select **16:9** (default widescreen for desktop and X) or **9:16** (vertical for TikTok profile, TikTok stories, and Instagram Reels).")
lines.append("6. **Paste Chosen Prompt**: Paste your chosen viral meme video prompt into the prompt field, or upload a previously generated meme image to animate it into a moving clip.")
lines.append("7. **Generate Video**: Press Enter. Qwen will process and render a cinematic 5-7 second viral video.")
lines.append("8. **Save File**: Click the download button on the video player to save the high-definition MP4 file.")
lines.append("9. **Publish Everywhere**: Copy the matching cross-platform social copy and deploy across TikTok, Instagram Reels, X Community, and the Telegram war room.")
lines.append("Done.")
lines.append("")
lines.append("### Engine 2: Meta AI Video & Animate (meta.ai)")
lines.append("Meta AI offers completely free text-to-video and image animation with zero subscription fees.")
lines.append("")
lines.append("Fast.")
lines.append("1. **Open Tool**: Go to `https://meta.ai` or open the Meta AI app on your phone.")
lines.append("2. **Sign in**: Sign in with any free Meta or Instagram profile.")
lines.append("3. **Image-to-Video Workflow**: Generate an image first, then click the **Animate** button on the picture to generate a 5-6 second motion video clip.")
lines.append("4. **Text-to-Video Workflow**: Type: `Create a video of:` followed by the copied video prompt.")
lines.append("5. **Download**: Click the download button on the video player to save the MP4.")
lines.append("6. **Post Directly**: Post to Instagram Reels and Facebook stories with pre-written tags.")
lines.append("Ready.")
lines.append("")
lines.append("### Engine 3: Grok Imagine on X")
lines.append("Grok provides fast generation directly inside your X browser workflow.")
lines.append("")
lines.append("Clean.")
lines.append("1. **Open Tool**: Visit `https://x.com/i/grok` or go to `https://grok.com`.")
lines.append("2. **Sign in**: Log in with your X account.")
lines.append("3. **Input Prompt**: In the chat box, type `/imagine` followed by your chosen prompt.")
lines.append("4. **Generate**: Press Enter. Grok produces high-contrast media variations.")
lines.append("5. **Download**: Click the media file to expand it, right-click, and choose **Save Image**.")
lines.append("6. **Deploy**: Post to the official $HUHCAT X community with the pre-formatted caption.")
lines.append("Direct.")
lines.append("")
lines.append("### Engine 4: Google VideoFX (labs.google/fx)")
lines.append("Google VideoFX gives access to Google's experimental video generation models for short cinematic clips.")
lines.append("")
lines.append("Swift.")
lines.append("1. **Open Tool**: Go to `https://labs.google/fx/tools/video-fx`.")
lines.append("2. **Sign in**: Log in with your standard Google credentials.")
lines.append("3. **Input Prompt**: Paste your copied 5-7 second video description into the prompt window.")
lines.append("4. **Generate**: Submit the message to produce high-definition experimental video clips.")
lines.append("5. **Save**: Click download to export the video file.")
lines.append("Locked.")
lines.append("")
lines.append("### Engine 5: Hailuo AI by Minimax (hailuoai.video)")
lines.append("Hailuo AI offers daily free video credits with industry-leading camera sweeps and realistic physical simulation.")
lines.append("")
lines.append("Boost.")
lines.append("1. **Open Tool**: Go to `https://hailuoai.video`.")
lines.append("2. **Sign in**: Create a free account with your email or Google login.")
lines.append("3. **Upload Image**: Click the image upload box and upload your generated HUHCAT meme photo.")
lines.append("4. **Add Camera Motion Prompt**: Paste the matching 5-7 second video animation prompt into the box.")
lines.append("5. **Generate**: Click Generate. Download your camera-swept MP4 clip.")
lines.append("Complete.")
lines.append("")
lines.append("---")
lines.append("")
lines.append("## Part 2: Cross-Platform Deployment Playbook")
lines.append("")
lines.append("Do not let your generated clips sit idle on your hard drive because viral reach requires deploying visual assets across algorithmic recommendation feeds simultaneously to capture compound traffic from multiple independent platforms. Strike everywhere. Act now.")
lines.append("")
lines.append("Deploy. Raid. Win.")
lines.append("")
lines.append("### 1. YouTube Shorts (Videos)")
lines.append("Vertical video on YouTube reaches millions of passive viewers through the Shorts algorithm without requiring an existing subscriber base because the recommendation engine serves entertaining short-form media directly to interested audiences based entirely on initial viewer retention and swipe-away rates.")
lines.append("")
lines.append("Specifications:")
lines.append("- Aspect Ratio: 9:16 vertical (1080x1920 pixels) or 1:1 square.")
lines.append("- Length: Five to sixty seconds.")
lines.append("- Format: MP4 or MOV container.")
lines.append("")
lines.append("Mobile Application Workflow:")
lines.append("1. Open the YouTube app on your mobile phone and tap the plus icon located in the center of the bottom navigation bar.")
lines.append("2. Select Create a Short from the popup drawer.")
lines.append("3. Tap the gallery thumbnail square in the bottom-left corner to access your device photo library.")
lines.append("4. Select your exported HUHCAT video animation and tap Done in the bottom-right corner to process the video duration.")
lines.append("5. Tap the checkmark icon in the bottom-right corner to open the editor.")
lines.append("6. Tap Next in the top-right corner to proceed to the upload details screen.")
lines.append("7. Enter your post title in the caption field, including the cashtag $HUHCAT and the hashtag #Shorts.")
lines.append("8. Tap the pencil edit icon on the video preview thumbnail in the top-left corner, scrub the timeline to pick the most comical facial frame, and tap Done.")
lines.append("9. Set Visibility to Public and confirm under Audience that you select No, it is not made for kids.")
lines.append("10. Tap the blue Upload Short button to broadcast your clip to the global Shorts feed.")
lines.append("Publish. Complete.")
lines.append("")
lines.append("Desktop Studio Workflow:")
lines.append("1. Open `https://studio.youtube.com` in your desktop web browser.")
lines.append("2. Click Create in the top-right corner and select Upload videos.")
lines.append("3. Drag and drop your vertical MP4 file into the window, then enter your title with $HUHCAT and #Shorts.")
lines.append("4. Paste your post caption and verification link into the description box.")
lines.append("5. Select No, it is not made for kids under Audience.")
lines.append("6. Click through the checks, choose Public visibility, and click Publish.")
lines.append("Done.")
lines.append("")
lines.append("### 2. TikTok Profile (Videos)")
lines.append("TikTok prioritizes high-completion short loops and pushes engaging five-second clips onto millions of For You pages without caring about your follower count as long as watch time and re-watch frequency remain strong.")
lines.append("")
lines.append("Specifications:")
lines.append("- Aspect Ratio: 9:16 vertical (1080x1920 pixels).")
lines.append("- Format: MP4 or MOV.")
lines.append("- Caption Limit: Up to 4,000 characters.")
lines.append("")
lines.append("Mobile Application Workflow:")
lines.append("1. Open the TikTok app and tap the plus icon in the center of the bottom navigation bar.")
lines.append("2. Tap the Upload square to the right of the red record button.")
lines.append("3. Select your five to seven second HUHCAT video clip and tap Next.")
lines.append("4. Tap Add sound at the top to select trending meme audio tracks.")
lines.append("5. Tap the red Next button in the bottom-right corner.")
lines.append("6. Paste your social caption into the description box, including $HUHCAT, #HUHCAT, #solana, and @HuhCatOnSol_.")
lines.append("7. Tap Select cover on the video preview, scrub to pick the peak bewildered cat face, add an on-screen text hook, and tap Save.")
lines.append("8. Confirm Who can watch this video is set to Everyone.")
lines.append("9. Confirm comments along with duets and stitches remain toggled on.")
lines.append("10. Tap the red Post button to distribute your clip across the algorithm.")
lines.append("Broadcast.")
lines.append("")
lines.append("Desktop Web Workflow:")
lines.append("1. Go to `https://www.tiktok.com/upload` in your desktop browser.")
lines.append("2. Drag and drop your MP4 file into the upload zone.")
lines.append("3. Enter your caption with cashtag $HUHCAT and project handle tags.")
lines.append("4. Pick your cover frame from the timeline slider.")
lines.append("5. Click the red Post button.")
lines.append("Shipped.")
lines.append("")
lines.append("### 3. TikTok Stories (Video Feeds and Photo Carousels)")
lines.append("Stories appear inside a glowing blue ring on your profile for twenty-four hours and capture immediate attention from active followers before vanishing into the digital ether.")
lines.append("")
lines.append("Specifications:")
lines.append("- Expiration: Active for twenty-four hours from posting.")
lines.append("- Media Types: Single video clips, single static photos, or multi-photo swipe carousels.")
lines.append("")
lines.append("Single Video or Photo Story Workflow:")
lines.append("1. Open the TikTok app and tap the plus icon at the bottom.")
lines.append("2. Tap Upload and select your generated HUHCAT photo or video.")
lines.append("3. Add text stickers or audio if desired.")
lines.append("4. Locate the bottom action buttons: note the red Next button and the light blue Your Story button.")
lines.append("5. Tap the light blue Your Story button to publish immediately to your twenty-four-hour story reel without posting to your main profile grid.")
lines.append("Speed.")
lines.append("")
lines.append("Photo Carousel Story Workflow:")
lines.append("1. Open TikTok and tap the plus icon.")
lines.append("2. Tap Upload.")
lines.append("3. Tap the Select multiple circular button in the bottom-left corner.")
lines.append("4. Select up to thirty-five images in your chosen sequence, starting with the meme hook and ending with Mission Control verification.")
lines.append("5. Tap the red Next button to enter Photo Mode.")
lines.append("6. Swipe horizontally to verify the slide order and tap Add sound to pair music.")
lines.append("7. Tap the light blue Your Story button to publish as a swipeable story carousel, or tap the red Post button to publish to the permanent profile feed.")
lines.append("Active.")
lines.append("")
lines.append("### 4. X Profile (Images and Videos)")
lines.append("Native media uploaded straight to X receives strong distribution across algorithmic timeline feeds because the algorithm explicitly deprioritizes external link previews while boosting posts that retain user attention on native video and high-contrast photographic media.")
lines.append("")
lines.append("Specifications:")
lines.append("- Image Limit: Up to four images per post (JPEG, PNG, WebP).")
lines.append("- Video Limit: One MP4 or MOV file up to two minutes and twenty seconds for standard accounts.")
lines.append("")
lines.append("Posting Workflow:")
lines.append("1. Open `https://x.com` or launch the X mobile application.")
lines.append("2. Click the blue Post button or tap the compose feather icon.")
lines.append("3. Click the media picture icon at the bottom of the composer box.")
lines.append("4. Select up to four static meme renders or one video animation file.")
lines.append("5. Write your text in the composer, incorporating $HUHCAT, #HUHCAT, @HuhCatOnSol_, and your verification link `https://jmthomasofficial.github.io/huhcat/mission-control/`.")
lines.append("6. Click Add description on static images to write accessibility keywords.")
lines.append("7. Click the blue Post button to broadcast to the global timeline.")
lines.append("Fired.")
lines.append("")
lines.append("### 5. X Community (Images and Videos)")
lines.append("Deploying content directly into the official HUHCAT X community coordinates holders and arms community raiders with instant retweet material while creating an active public archive of community engagement.")
lines.append("")
lines.append("Target Community URL:")
lines.append("`https://x.com/i/communities/2033348205224530334`")
lines.append("")
lines.append("Direct Community Feed Workflow:")
lines.append("1. Open `https://x.com/i/communities/2033348205224530334` in your browser or mobile app.")
lines.append("2. Click the black Join button if you are not already an enrolled member.")
lines.append("3. Locate the composer box at the top of the community feed with the prompt What is happening?!.")
lines.append("4. Confirm the green HUHCAT community icon is visible above the input field.")
lines.append("5. Click the media icon and attach your meme images or video file.")
lines.append("6. Paste your raid caption, cashtag $HUHCAT, and call to action.")
lines.append("7. Click the blue Post button to drop your content directly into the war room.")
lines.append("Raid.")
lines.append("")
lines.append("Composer Dropdown Workflow:")
lines.append("1. Click the standard Post compose button from any feed on X.")
lines.append("2. Tap the audience selector button at the top of the composer window, which defaults to Everyone.")
lines.append("3. Select HUHCAT from your joined communities list.")
lines.append("4. Attach your media, paste your text, and click Post.")
lines.append("Synced.")
lines.append("")
lines.append("### 6. Instagram Profile Feed (Images and Videos)")
lines.append("Permanent feed posts anchor your visual brand identity and support multi-image swipe carousels that encourage repeated user interactions and profile visits.")
lines.append("")
lines.append("Specifications:")
lines.append("- Aspect Ratio: 1:1 square (1080x1080 pixels) or 4:5 vertical portrait (1080x1350 pixels).")
lines.append("- Carousel Limit: Up to twenty photos or videos in a single post.")
lines.append("")
lines.append("Mobile Application Workflow:")
lines.append("1. Open the Instagram app and tap the plus icon.")
lines.append("2. Select POST from the bottom tray.")
lines.append("3. For single images, tap the double-arrow crop icon on the preview to select 1:1 square or 4:5 vertical portrait framing.")
lines.append("4. For multi-photo carousels, tap the stacked squares icon and choose up to twenty photos or videos in sequence.")
lines.append("5. Tap Next in the top-right corner.")
lines.append("6. Add background music if desired by tapping the audio note icon.")
lines.append("7. Tap Next to enter the final sharing screen.")
lines.append("8. Write your post description, adding $HUHCAT, #HUHCAT, and @HuhCatOnSol_.")
lines.append("9. Tap the blue Share button to publish to your profile grid.")
lines.append("Locked.")
lines.append("")
lines.append("Desktop Web Workflow:")
lines.append("1. Open `https://www.instagram.com` in your desktop browser.")
lines.append("2. Click Create in the left sidebar navigation menu.")
lines.append("3. Drag and drop your image or video files.")
lines.append("4. Choose 1:1 or 4:5 crop, enter your caption with tags, and click Share.")
lines.append("Shared.")
lines.append("")
lines.append("### 7. Instagram Reels (Videos and Images)")
lines.append("Instagram Reels deliver discovery reach by serving full-screen vertical video to users browsing algorithmic topic feeds who do not follow your account.")
lines.append("")
lines.append("Specifications:")
lines.append("- Aspect Ratio: 9:16 vertical full-screen (1080x1920 pixels).")
lines.append("- Length: Up to ninety seconds, with five to seven seconds performing best for loop completion rates.")
lines.append("")
lines.append("Mobile Application Workflow:")
lines.append("1. Open Instagram, tap the plus icon, and slide the bottom selector to REEL.")
lines.append("2. Tap the gallery square in the bottom-left corner to access your files.")
lines.append("3. Select your five to seven second video clip, or select multiple still photos to generate a beat-synced photo reel.")
lines.append("4. Tap Add in the top-right corner, then tap Next.")
lines.append("5. Tap the Audio music note icon to browse trending audio tracks and balance volume levels.")
lines.append("6. Tap the Aa text tool to place a bold hook sticker over the video.")
lines.append("7. Tap Next to open the share settings screen.")
lines.append("8. Tap Edit cover on the preview, scrub to choose a comical facial frame, or upload a custom static still from your photo library, and tap Done.")
lines.append("9. Write your post caption with $HUHCAT, #HUHCAT, and relevant hashtags.")
lines.append("10. Verify that Also share to feed is turned on so your followers see the Reel on your grid.")
lines.append("11. Tap the blue Share button.")
lines.append("Live.")
lines.append("")
lines.append("### 8. Pinterest (Images and Videos)")
lines.append("Pinterest is a visual search engine where pins stay discoverable for months through keyword search queries long after traditional social media posts disappear from chronological feeds.")
lines.append("")
lines.append("Specifications:")
lines.append("- Static Pin Ratio: 2:3 vertical (1000x1500 pixels) or 1:1 square.")
lines.append("- Video Pin Ratio: 9:16 vertical or 2:3 vertical (under two gigabytes, MP4 or MOV).")
lines.append("- Destination URL: Direct link to project resources.")
lines.append("")
lines.append("Desktop Web Workflow:")
lines.append("1. Go to `https://www.pinterest.com/pin-creation-tool/` in your web browser.")
lines.append("2. Drag and drop your meme image or MP4 video into the upload box.")
lines.append("3. In the Title field, type an informative headline: Huh Cat Taken Over by Community // $HUHCAT Solana Memecoin.")
lines.append("4. In the Description field, enter your explanation and include searchable terms: $HUHCAT, Solana meme cat, crypto humor, Ben Cat.")
lines.append("5. In the Link field, paste the destination link: `https://jmthomasofficial.github.io/huhcat/mission-control/`.")
lines.append("6. Open the board dropdown in the top-right corner and choose or create a board named Solana Memes or Crypto Culture.")
lines.append("7. Click the red Publish button.")
lines.append("Indexed.")
lines.append("")
lines.append("Mobile Application Workflow:")
lines.append("1. Open the Pinterest mobile app.")
lines.append("2. Tap the plus icon in the bottom navigation bar and select Pin.")
lines.append("3. Select your photo or video from your device photo library and tap Next.")
lines.append("4. Enter your Title, Description, and paste the Destination Link.")
lines.append("5. Tap Next, pick your target board, and tap Save.")
lines.append("Complete.")
lines.append("")
lines.append("---")
lines.append("")
lines.append("## Part 3: The 100 Viral Meme & Video Studio Arsenals")
lines.append("")

current_cat = ""
for m in memes:
    if m['category_name'] != current_cat:
        current_cat = m['category_name']
        lines.append(f"### Lane: {current_cat}")
        lines.append("Forward.")
        lines.append("")
    
    lines.append(f"#### #{m['num']:03d} // {m['title']}")
    lines.append("Deploy. Raid.")
    lines.append(f"**Category**: {m['category_name']}.")
    lines.append(f"**Tags**: `{'`, `'.join(m['tags'])}`")
    lines.append("Strike.")
    lines.append("")
    lines.append("**Step 1: AI Static Image Prompt (Qwen-Image 3.0 / Grok / Gemini):**")
    prompt_flow = m['prompt'].rstrip('. ') + ", rendered with photographic realism, ultra-sharp detail plus authentic optical lens depth."
    prompt_single = re.sub(r'\.\s+', ', ', prompt_flow)
    lines.append(f"> {prompt_single}")
    lines.append("")
    lines.append("Motion.")
    lines.append("**Step 2: 5-7s Viral Video Animation Prompt (Qwen Video / Meta AI / Hailuo):**")
    video_flow = m['video_prompt'].rstrip('. ') + ", smooth camera physics, cinematic volumetric lighting, 6-second fluid loop."
    video_single = re.sub(r'\.\s+', ', ', video_flow)
    lines.append(f"> {video_single}")
    lines.append("")
    lines.append("Fire.")
    lines.append("**Step 3: Cross-Platform Post Caption & Metadata (X / TikTok / Reels):**")
    lines.append(f"```text\n{m['caption']}\n```")
    lines.append("Verified.")
    lines.append("")
    lines.append("---")
    lines.append("")

content = '\n'.join(lines)
with open('MEME-FACTORY-100.md', 'w', encoding='utf-8') as f:
    f.write(content)

print("Generated streamlined MEME-FACTORY-100.md with 100 image + video prompts!")
